# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WUnderground(object):
    def setupUi(self, WUnderground):
        WUnderground.setObjectName("WUnderground")
        WUnderground.resize(1051, 515)
        self.centralwidget = QtWidgets.QWidget(WUnderground)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(199, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.label_11 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)

        self.comboBox_WeatherStation = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_WeatherStation.setFont(font)
        self.comboBox_WeatherStation.setObjectName("comboBox_WeatherStation")
        self.verticalLayout_5.addWidget(self.comboBox_WeatherStation)

        self.labelFrom = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelFrom.setFont(font)
        self.labelFrom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelFrom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFrom.setObjectName("labelFrom")
        self.verticalLayout_5.addWidget(self.labelFrom)

        self.dateFrom = QtWidgets.QDateEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dateFrom.setFont(font)
        self.dateFrom.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.dateFrom.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.verticalLayout_5.addWidget(self.dateFrom)

        self.labelTo = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelTo.setFont(font)
        self.labelTo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTo.setObjectName("labelTo")
        self.verticalLayout_5.addWidget(self.labelTo)

        self.dateTo = QtWidgets.QDateEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dateTo.setFont(font)
        self.dateTo.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.dateTo.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.verticalLayout_5.addWidget(self.dateTo)
        self.verticalLayout.addWidget(self.frame_2)

        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.btnFetchData = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnFetchData.setFont(font)
        self.btnFetchData.setObjectName("btnFetchData")
        self.verticalLayout_3.addWidget(self.btnFetchData, 0, QtCore.Qt.AlignTop)
        self.btnClearData = QtWidgets.QPushButton(self.frame_6)
        self.btnClearData.setObjectName("btnClearData")
        self.verticalLayout_3.addWidget(self.btnClearData)
        self.verticalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.frame_3)

        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setContentsMargins(1, 1, 11, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(350, 200))
        self.frame_10.setMaximumSize(QtCore.QSize(350, 400))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(11, 7, -1, 1)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.grid_station_info_id = QtWidgets.QGridLayout()
        self.grid_station_info_id.setObjectName("grid_station_info_id")

        self.label_info_station_id = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(False)
        self.label_info_station_id.setFont(font)
        self.label_info_station_id.setObjectName("label_info_station_id")
        self.grid_station_info_id.addWidget(self.label_info_station_id, 0, 1, 1, 1)

        self.label_8 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.grid_station_info_id.addWidget(self.label_8, 0, 0, 1, 1)

        self.label_info_date = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(False)
        self.label_info_date.setFont(font)
        self.label_info_date.setObjectName("label_info_date")
        self.grid_station_info_id.addWidget(self.label_info_date, 0, 3, 1, 1)

        self.label_15 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.grid_station_info_id.addWidget(self.label_15, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.grid_station_info_id)
        self.gridLayoutMain = QtWidgets.QGridLayout()
        self.gridLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayoutMain.setHorizontalSpacing(11)
        self.gridLayoutMain.setVerticalSpacing(4)
        self.gridLayoutMain.setObjectName("gridLayoutMain")

        self.txtTempLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTempLow.sizePolicy().hasHeightForWidth())
        self.txtTempLow.setSizePolicy(sizePolicy)
        self.txtTempLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtTempLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTempLow.setReadOnly(True)
        self.txtTempLow.setObjectName("txtTempLow")
        self.gridLayoutMain.addWidget(self.txtTempLow, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())

        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayoutMain.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())

        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayoutMain.addWidget(self.label_5, 2, 0, 1, 1)
        self.txtWindSpeedAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindSpeedAvg.sizePolicy().hasHeightForWidth())
        self.txtWindSpeedAvg.setSizePolicy(sizePolicy)
        self.txtWindSpeedAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindSpeedAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindSpeedAvg.setReadOnly(True)
        self.txtWindSpeedAvg.setObjectName("txtWindSpeedAvg")
        self.gridLayoutMain.addWidget(self.txtWindSpeedAvg, 4, 3, 1, 1)
        self.txtDewPointAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDewPointAvg.sizePolicy().hasHeightForWidth())
        self.txtDewPointAvg.setSizePolicy(sizePolicy)
        self.txtDewPointAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtDewPointAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDewPointAvg.setReadOnly(True)
        self.txtDewPointAvg.setObjectName("txtDewPointAvg")
        self.gridLayoutMain.addWidget(self.txtDewPointAvg, 2, 3, 1, 1)
        self.txtWindGustAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindGustAvg.sizePolicy().hasHeightForWidth())
        self.txtWindGustAvg.setSizePolicy(sizePolicy)
        self.txtWindGustAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindGustAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindGustAvg.setReadOnly(True)
        self.txtWindGustAvg.setObjectName("txtWindGustAvg")
        self.gridLayoutMain.addWidget(self.txtWindGustAvg, 5, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())

        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(96, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayoutMain.addWidget(self.label_4, 1, 0, 1, 1)
        self.txtWindChillHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindChillHigh.sizePolicy().hasHeightForWidth())
        self.txtWindChillHigh.setSizePolicy(sizePolicy)
        self.txtWindChillHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindChillHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindChillHigh.setReadOnly(True)
        self.txtWindChillHigh.setObjectName("txtWindChillHigh")
        self.gridLayoutMain.addWidget(self.txtWindChillHigh, 6, 1, 1, 1)
        self.txtWindChillAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindChillAvg.sizePolicy().hasHeightForWidth())
        self.txtWindChillAvg.setSizePolicy(sizePolicy)
        self.txtWindChillAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindChillAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindChillAvg.setReadOnly(True)
        self.txtWindChillAvg.setObjectName("txtWindChillAvg")
        self.gridLayoutMain.addWidget(self.txtWindChillAvg, 6, 3, 1, 1)
        self.txtDewPointHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDewPointHigh.sizePolicy().hasHeightForWidth())
        self.txtDewPointHigh.setSizePolicy(sizePolicy)
        self.txtDewPointHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtDewPointHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDewPointHigh.setReadOnly(True)
        self.txtDewPointHigh.setObjectName("txtDewPointHigh")
        self.gridLayoutMain.addWidget(self.txtDewPointHigh, 2, 1, 1, 1)

        self.label = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutMain.addWidget(self.label, 0, 1, 1, 1)
        self.txtHeatIndexLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeatIndexLow.sizePolicy().hasHeightForWidth())
        self.txtHeatIndexLow.setSizePolicy(sizePolicy)
        self.txtHeatIndexLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtHeatIndexLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHeatIndexLow.setReadOnly(True)
        self.txtHeatIndexLow.setObjectName("txtHeatIndexLow")
        self.gridLayoutMain.addWidget(self.txtHeatIndexLow, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayoutMain.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayoutMain.addWidget(self.label_3, 0, 3, 1, 1)
        self.txtWindGustHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindGustHigh.sizePolicy().hasHeightForWidth())
        self.txtWindGustHigh.setSizePolicy(sizePolicy)
        self.txtWindGustHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindGustHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindGustHigh.setReadOnly(True)
        self.txtWindGustHigh.setObjectName("txtWindGustHigh")
        self.gridLayoutMain.addWidget(self.txtWindGustHigh, 5, 1, 1, 1)
        self.txtWindGustLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindGustLow.sizePolicy().hasHeightForWidth())
        self.txtWindGustLow.setSizePolicy(sizePolicy)
        self.txtWindGustLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindGustLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindGustLow.setReadOnly(True)
        self.txtWindGustLow.setObjectName("txtWindGustLow")
        self.gridLayoutMain.addWidget(self.txtWindGustLow, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayoutMain.addWidget(self.label_12, 4, 0, 1, 1)
        self.txtDewPointLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDewPointLow.sizePolicy().hasHeightForWidth())
        self.txtDewPointLow.setSizePolicy(sizePolicy)
        self.txtDewPointLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtDewPointLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDewPointLow.setReadOnly(True)
        self.txtDewPointLow.setObjectName("txtDewPointLow")
        self.gridLayoutMain.addWidget(self.txtDewPointLow, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayoutMain.addWidget(self.label_2, 0, 2, 1, 1)
        self.txtHeatIndexHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeatIndexHigh.sizePolicy().hasHeightForWidth())
        self.txtHeatIndexHigh.setSizePolicy(sizePolicy)
        self.txtHeatIndexHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtHeatIndexHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHeatIndexHigh.setReadOnly(True)
        self.txtHeatIndexHigh.setObjectName("txtHeatIndexHigh")
        self.gridLayoutMain.addWidget(self.txtHeatIndexHigh, 3, 1, 1, 1)
        self.txtWindChillLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindChillLow.sizePolicy().hasHeightForWidth())
        self.txtWindChillLow.setSizePolicy(sizePolicy)
        self.txtWindChillLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindChillLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindChillLow.setReadOnly(True)
        self.txtWindChillLow.setObjectName("txtWindChillLow")
        self.gridLayoutMain.addWidget(self.txtWindChillLow, 6, 2, 1, 1)
        self.txtHeatIndexAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeatIndexAvg.sizePolicy().hasHeightForWidth())
        self.txtHeatIndexAvg.setSizePolicy(sizePolicy)
        self.txtHeatIndexAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtHeatIndexAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHeatIndexAvg.setReadOnly(True)
        self.txtHeatIndexAvg.setObjectName("txtHeatIndexAvg")
        self.gridLayoutMain.addWidget(self.txtHeatIndexAvg, 3, 3, 1, 1)
        self.txtTempAvg = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTempAvg.sizePolicy().hasHeightForWidth())
        self.txtTempAvg.setSizePolicy(sizePolicy)
        self.txtTempAvg.setMaximumSize(QtCore.QSize(60, 60))
        self.txtTempAvg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTempAvg.setReadOnly(True)
        self.txtTempAvg.setObjectName("txtTempAvg")
        self.gridLayoutMain.addWidget(self.txtTempAvg, 1, 3, 1, 1)
        self.txtWindSpeedHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindSpeedHigh.sizePolicy().hasHeightForWidth())
        self.txtWindSpeedHigh.setSizePolicy(sizePolicy)
        self.txtWindSpeedHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindSpeedHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindSpeedHigh.setReadOnly(True)
        self.txtWindSpeedHigh.setObjectName("txtWindSpeedHigh")
        self.gridLayoutMain.addWidget(self.txtWindSpeedHigh, 4, 1, 1, 1)
        self.txtWindSpeedLow = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWindSpeedLow.sizePolicy().hasHeightForWidth())
        self.txtWindSpeedLow.setSizePolicy(sizePolicy)
        self.txtWindSpeedLow.setMaximumSize(QtCore.QSize(60, 60))
        self.txtWindSpeedLow.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWindSpeedLow.setReadOnly(True)
        self.txtWindSpeedLow.setObjectName("txtWindSpeedLow")
        self.gridLayoutMain.addWidget(self.txtWindSpeedLow, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayoutMain.addWidget(self.label_6, 3, 0, 1, 1)
        self.txtTempHigh = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTempHigh.sizePolicy().hasHeightForWidth())
        self.txtTempHigh.setSizePolicy(sizePolicy)
        self.txtTempHigh.setMinimumSize(QtCore.QSize(0, 0))
        self.txtTempHigh.setMaximumSize(QtCore.QSize(60, 60))
        self.txtTempHigh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTempHigh.setReadOnly(True)
        self.txtTempHigh.setObjectName("txtTempHigh")
        self.gridLayoutMain.addWidget(self.txtTempHigh, 1, 1, 1, 1)
        self.gridLayoutMain.setColumnMinimumWidth(0, 10)
        self.verticalLayout_6.addLayout(self.gridLayoutMain)
        self.gridLayout_Pressure = QtWidgets.QGridLayout()
        self.gridLayout_Pressure.setHorizontalSpacing(11)
        self.gridLayout_Pressure.setVerticalSpacing(4)
        self.gridLayout_Pressure.setObjectName("gridLayout_Pressure")
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_Pressure.addWidget(self.label_18, 0, 4, 1, 1)
        self.txtPressureMin = QtWidgets.QLineEdit(self.frame_10)
        self.txtPressureMin.setMaximumSize(QtCore.QSize(60, 60))
        self.txtPressureMin.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPressureMin.setReadOnly(True)
        self.txtPressureMin.setObjectName("txtPressureMin")
        self.gridLayout_Pressure.addWidget(self.txtPressureMin, 1, 1, 1, 1)
        self.txtPressureMax = QtWidgets.QLineEdit(self.frame_10)
        self.txtPressureMax.setMaximumSize(QtCore.QSize(60, 60))
        self.txtPressureMax.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPressureMax.setReadOnly(True)
        self.txtPressureMax.setObjectName("txtPressureMax")
        self.gridLayout_Pressure.addWidget(self.txtPressureMax, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_Pressure.addWidget(self.label_21, 0, 3, 1, 1)
        self.txtPressureTrend = QtWidgets.QLineEdit(self.frame_10)
        self.txtPressureTrend.setMaximumSize(QtCore.QSize(60, 60))
        self.txtPressureTrend.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPressureTrend.setReadOnly(True)
        self.txtPressureTrend.setObjectName("txtPressureTrend")
        self.gridLayout_Pressure.addWidget(self.txtPressureTrend, 1, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_Pressure.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_Pressure.addWidget(self.label_20, 0, 1, 1, 1)
        self.gridLayout_Pressure.setColumnMinimumWidth(0, 10)
        self.verticalLayout_6.addLayout(self.gridLayout_Pressure)
        self.gridLayout_Precip = QtWidgets.QGridLayout()
        self.gridLayout_Precip.setHorizontalSpacing(11)
        self.gridLayout_Precip.setVerticalSpacing(4)
        self.gridLayout_Precip.setObjectName("gridLayout_Precip")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_Precip.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_Precip.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_Precip.addWidget(self.label_7, 1, 0, 1, 1)
        self.txtPrecipationRate = QtWidgets.QLineEdit(self.frame_10)
        self.txtPrecipationRate.setMaximumSize(QtCore.QSize(60, 60))
        self.txtPrecipationRate.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPrecipationRate.setReadOnly(True)
        self.txtPrecipationRate.setObjectName("txtPrecipationRate")
        self.gridLayout_Precip.addWidget(self.txtPrecipationRate, 1, 1, 1, 1)
        self.txtPrecipationTotal = QtWidgets.QLineEdit(self.frame_10)
        self.txtPrecipationTotal.setMaximumSize(QtCore.QSize(60, 60))
        self.txtPrecipationTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPrecipationTotal.setReadOnly(True)
        self.txtPrecipationTotal.setObjectName("txtPrecipationTotal")
        self.gridLayout_Precip.addWidget(self.txtPrecipationTotal, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_Precip.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_Precip.setColumnMinimumWidth(0, 10)
        self.verticalLayout_6.addLayout(self.gridLayout_Precip)
        self.horizontalLayout.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.widgetChart_CurrentQuarter = QtWidgets.QWidget(self.frame_9)
        self.widgetChart_CurrentQuarter.setGeometry(QtCore.QRect(10, 40, 251, 111))
        self.widgetChart_CurrentQuarter.setObjectName("widgetChart_CurrentQuarter")

        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(30, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.widgetChart_PreviousQuarter = QtWidgets.QWidget(self.frame_9)
        self.widgetChart_PreviousQuarter.setGeometry(QtCore.QRect(20, 250, 251, 111))
        self.widgetChart_PreviousQuarter.setObjectName("widgetChart_PreviousQuarter")
        self.horizontalLayout.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelMonthlyData = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelMonthlyData.setFont(font)
        self.labelMonthlyData.setObjectName("labelMonthlyData")
        self.verticalLayout_7.addWidget(self.labelMonthlyData)
        self.tableViewMonthly = QtWidgets.QTableView(self.frame_4)
        self.tableViewMonthly.setObjectName("tableViewMonthly")
        self.verticalLayout_7.addWidget(self.tableViewMonthly)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_5)
        WUnderground.setCentralWidget(self.centralwidget)

        # ##############################
        #    Start Menu bar items here
        # ##############################

        self.menubar = QtWidgets.QMenuBar(WUnderground)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 21))
        self.menubar.setObjectName("menubar")

        """ Create Main Menu options """
        # File Menu
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        # Edit Menu
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")

        # Help Menu
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        WUnderground.setMenuBar(self.menubar)

        """ Create Menu Actions """
        # File Menu
        self.actionExport = QtWidgets.QAction(WUnderground)
        self.actionExport.setObjectName("actionExport")

        self.actionExit = QtWidgets.QAction(WUnderground)
        self.actionExit.setObjectName("actionExit")

        # Edit Menu
        self.actionAPI_Key = QtWidgets.QAction(WUnderground)
        self.actionAPI_Key.setObjectName("actionAPI_Key")

        self.actionAPIDelete_Key = QtWidgets.QAction(WUnderground)
        self.actionAPIDelete_Key.setObjectName("actionAPIDelete_Key")

        self.actionMultiple_Stations = QtWidgets.QAction(WUnderground)
        self.actionMultiple_Stations.setObjectName("actionMultiple_Stations")

        self.actionAddStation = QtWidgets.QAction(WUnderground)
        self.actionAddStation.setObjectName("actionAddStation")

        self.actionDeleteStation = QtWidgets.QAction(WUnderground)
        self.actionDeleteStation.setObjectName("actionDeleteStation")

        # Help Menu
        self.actionAbout = QtWidgets.QAction(WUnderground)
        self.actionAbout.setObjectName("actionAbout")

        """ Menu Actions """
        # File Menu
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)

        # Edit Menu
        self.menuEdit.addAction(self.actionAPI_Key)
        self.menuEdit.addAction(self.actionAPIDelete_Key)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMultiple_Stations)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAddStation)
        self.menuEdit.addAction(self.actionDeleteStation)

        # Help Menu
        self.menuHelp.addAction(self.actionAbout)

        # Add actions to the menu bar
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.statusbar = QtWidgets.QStatusBar(WUnderground)
        self.statusbar.setObjectName("statusbar")
        WUnderground.setStatusBar(self.statusbar)

        # set the text size
        self.set_font_size()

        self.retranslateUi(WUnderground)
        QtCore.QMetaObject.connectSlotsByName(WUnderground)

    def set_font_size(self):
        font = QtGui.QFont()
        font.setPointSize(9)

        font_bold = QtGui.QFont()
        font_bold.setBold(True)
        font_bold.setPointSize(8)

        self.txtTempLow.setFont(font)
        self.txtTempHigh.setFont(font)
        self.txtTempAvg.setFont(font)
        self.txtDewPointHigh.setFont(font)
        self.txtDewPointAvg.setFont(font)
        self.txtDewPointLow.setFont(font)
        self.txtHeatIndexLow.setFont(font)
        self.txtHeatIndexAvg.setFont(font)
        self.txtHeatIndexHigh.setFont(font)
        self.txtWindSpeedAvg.setFont(font)
        self.txtWindSpeedLow.setFont(font)
        self.txtWindSpeedHigh.setFont(font)
        self.txtWindGustAvg.setFont(font)
        self.txtWindGustLow.setFont(font)
        self.txtWindGustHigh.setFont(font)
        self.txtWindChillAvg.setFont(font)
        self.txtWindChillLow.setFont(font)
        self.txtWindChillHigh.setFont(font)
        self.txtPressureMax.setFont(font)
        self.txtPressureMin.setFont(font)
        self.txtPressureTrend.setFont(font)
        self.txtPrecipationTotal.setFont(font)
        self.txtPrecipationRate.setFont(font)

        self.label_8.setFont(font_bold)
        self.label_info_station_id.setFont(font)

        self.label_15.setFont(font_bold)
        self.label_info_date.setFont(font)

        self.btnClearData.setFont(font)

    def retranslateUi(self, WUnderground):
        _translate = QtCore.QCoreApplication.translate
        WUnderground.setWindowTitle(_translate("WUnderground", "WUnderground Weather Data Collection"))
        self.label_11.setText(_translate("WUnderground", "Weather Station:"))
        self.labelFrom.setText(_translate("WUnderground", "From:"))
        self.labelTo.setText(_translate("WUnderground", "To:"))
        self.btnFetchData.setText(_translate("WUnderground", "Fetch Data"))
        self.btnClearData.setText(_translate("WUnderground", "Clear Data"))
        self.label_info_station_id.setText(_translate("WUnderground", "Station Name"))
        self.label_8.setText(_translate("WUnderground", "Station Name:"))
        self.label_info_date.setText(_translate("WUnderground", "Info Detail Date"))
        self.label_15.setText(_translate("WUnderground", "Record Date:"))
        self.label_14.setText(_translate("WUnderground", "Wind Chill:"))
        self.label_5.setText(_translate("WUnderground", "Dew Point:"))
        self.label_4.setText(_translate("WUnderground", "Temperature:"))
        self.label.setText(_translate("WUnderground", "High"))
        self.label_13.setText(_translate("WUnderground", "Wind Gust:"))
        self.label_3.setText(_translate("WUnderground", "Average"))
        self.label_12.setText(_translate("WUnderground", "Wind Speed:"))
        self.label_2.setText(_translate("WUnderground", "Low"))
        self.label_6.setText(_translate("WUnderground", "Heat Index:"))
        self.label_18.setText(_translate("WUnderground", "Trend"))
        self.label_21.setText(_translate("WUnderground", "Max"))
        self.label_19.setText(_translate("WUnderground", "Pressure:"))
        self.label_20.setText(_translate("WUnderground", "Min"))
        self.label_10.setText(_translate("WUnderground", "Total"))
        self.label_9.setText(_translate("WUnderground", "Rate"))
        self.label_7.setText(_translate("WUnderground", "Precipitation:"))
        self.label_16.setText(_translate("WUnderground", "Current Quarter (chart)"))
        self.label_17.setText(_translate("WUnderground", "Previous Quarter (chart)"))
        self.labelMonthlyData.setText(_translate("WUnderground", "Monthly Data"))

        self.menuFile.setTitle(_translate("WUnderground", "File"))
        self.menuEdit.setTitle(_translate("WUnderground", "Edit"))
        self.menuHelp.setTitle(_translate("WUnderground", "Help"))

        self.actionExport.setText(_translate("WUnderground", "Export"))
        self.actionExit.setText(_translate("WUnderground", "Exit"))

        self.actionAPI_Key.setText(_translate("WUnderground", "Add API Keys"))
        self.actionAPIDelete_Key.setText(_translate("WUnderground", "Delete API Key"))

        self.actionMultiple_Stations.setText(_translate("WUnderground", "Select Multiple Stations"))

        self.actionAddStation.setText(_translate("WUnderground", "Add Weather Station"))
        self.actionDeleteStation.setText(_translate("WUnderground", "Delete Weather Station"))

        self.actionAbout.setText(_translate("WUnderground", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WUnderground = QtWidgets.QMainWindow()
    ui = Ui_WUnderground()
    ui.setupUi(WUnderground)
    WUnderground.show()
    sys.exit(app.exec_())
