# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(433, 409)
        self.labelFrom = QtWidgets.QLabel(SecondWindow)
        self.labelFrom.setGeometry(QtCore.QRect(30, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFrom.setFont(font)
        self.labelFrom.setObjectName("labelFrom")
        self.dateTo = QtWidgets.QDateEdit(SecondWindow)
        self.dateTo.setGeometry(QtCore.QRect(279, 30, 121, 23))
        self.dateTo.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.labelTo = QtWidgets.QLabel(SecondWindow)
        self.labelTo.setGeometry(QtCore.QRect(280, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTo.setFont(font)
        self.labelTo.setObjectName("labelTo")
        self.dateFrom = QtWidgets.QDateEdit(SecondWindow)
        self.dateFrom.setGeometry(QtCore.QRect(30, 30, 121, 23))
        self.dateFrom.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateFrom.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.dateFrom.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setCurrentSectionIndex(0)
        self.dateFrom.setObjectName("dateFrom")
        self.btnSearch = QtWidgets.QPushButton(SecondWindow)
        self.btnSearch.setGeometry(QtCore.QRect(30, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.btnCancel = QtWidgets.QPushButton(SecondWindow)
        self.btnCancel.setGeometry(QtCore.QRect(230, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.listStationMainList = QtWidgets.QListWidget(SecondWindow)
        self.listStationMainList.setGeometry(QtCore.QRect(30, 70, 121, 192))
        self.listStationMainList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listStationMainList.setObjectName("listStationMainList")
        self.listStationSearch = QtWidgets.QListWidget(SecondWindow)
        self.listStationSearch.setGeometry(QtCore.QRect(280, 70, 121, 192))
        self.listStationSearch.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listStationSearch.setObjectName("listStationSearch")
        self.progressBar = QtWidgets.QProgressBar(SecondWindow)
        self.progressBar.setVisible(False)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.btnAdd = QtWidgets.QPushButton(SecondWindow)
        self.btnAdd.setGeometry(QtCore.QRect(160, 110, 111, 25))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(SecondWindow)
        self.btnRemove.setGeometry(QtCore.QRect(160, 180, 111, 25))
        self.btnRemove.setObjectName("btnRemove")
        self.labelSearchStatus = QtWidgets.QLabel(SecondWindow)
        self.labelSearchStatus.setGeometry(QtCore.QRect(30, 280, 121, 16))
        self.labelSearchStatus.setObjectName("labelSearchStatus")
        self.textDateCheck = QtWidgets.QTextEdit(SecondWindow)
        self.textDateCheck.setGeometry(QtCore.QRect(30, 370, 371, 21))
        self.textDateCheck.setStyleSheet("color: rgb(170, 0, 0);")
        self.textDateCheck.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDateCheck.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDateCheck.setMarkdown("")
        self.textDateCheck.setObjectName("textDateCheck")
        self.btnAddAll = QtWidgets.QPushButton(SecondWindow)
        self.btnAddAll.setGeometry(QtCore.QRect(160, 140, 111, 25))
        self.btnAddAll.setObjectName("btnAddAll")
        self.btnRemoveAll = QtWidgets.QPushButton(SecondWindow)
        self.btnRemoveAll.setGeometry(QtCore.QRect(160, 210, 111, 25))
        self.btnRemoveAll.setObjectName("btnRemoveAll")

        self.retranslateUi(SecondWindow)
        self.btnCancel.clicked.connect(SecondWindow.close)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)
        SecondWindow.setTabOrder(self.dateFrom, self.dateTo)
        SecondWindow.setTabOrder(self.dateTo, self.listStationMainList)
        SecondWindow.setTabOrder(self.listStationMainList, self.listStationSearch)
        SecondWindow.setTabOrder(self.listStationSearch, self.btnAdd)
        SecondWindow.setTabOrder(self.btnAdd, self.btnAddAll)
        SecondWindow.setTabOrder(self.btnAddAll, self.btnRemove)
        SecondWindow.setTabOrder(self.btnRemove, self.btnRemoveAll)
        SecondWindow.setTabOrder(self.btnRemoveAll, self.btnSearch)
        SecondWindow.setTabOrder(self.btnSearch, self.textDateCheck)
        SecondWindow.setTabOrder(self.textDateCheck, self.btnCancel)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "SecondWindow"))
        self.labelFrom.setText(_translate("SecondWindow", "From Date"))
        self.labelTo.setText(_translate("SecondWindow", "To Date"))
        self.btnSearch.setText(_translate("SecondWindow", "Search"))
        self.btnCancel.setText(_translate("SecondWindow", "Cancel"))
        self.btnAdd.setText(_translate("SecondWindow", "Add >"))
        self.btnRemove.setText(_translate("SecondWindow", "< Remove"))
        self.labelSearchStatus.setText(_translate("SecondWindow", "Search Status"))
        self.textDateCheck.setHtml(_translate("SecondWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.btnAddAll.setText(_translate("SecondWindow", "Add All >>"))
        self.btnRemoveAll.setText(_translate("SecondWindow", "<< Remove All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QWidget()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
